### PR TITLE
Fixed readme

### PR DESCRIPTION
**Pull request by vghfr**
You do **not** want to replace the gamedata file with this one, as it will erase stock data. If you meant merging the folders, there should be clarification that it is to be merged not replaced

### CODE REVIEW

**Comment by vghfr** [comment]
Also, you should have the actual code on the repo so that people can contribute 😀

**Comment by Fossilized4** [comment]
Thank you for pointing this out. I will tweak the ReadMe myself to change it to say "merge" instead.

**Comment by Fossilized4** [comment]
> Also, you should have the actual code on the repo so that people can contribute 😀


What actual code?

**Comment by vghfr** [comment]
> > Also, you should have the actual code on the repo so that people can contribute 😀
> 
> What actual code?

The source code, not just the mod. ie, the csharp code.

**Comment by Fossilized4** [comment]
There is no source code. Everything is already included. There is no need for any csharp code

**Pull request closed without merging**
